In [89]:
# Librerias generales
import pandas as pd
import numpy as np
import sqlite3 as sql ### para conectarse a BD
from sklearn.impute import SimpleImputer

# Librerias e visualización
import seaborn as sns
import matplotlib.pyplot as plt

In [44]:
df_cronicos = pd.read_excel('RETO_df_cronicos.xlsx')
df_cronicos.head()

,YEAR,MES,Fecha diligenciamiento,Hora,AtenciÃ³n,Ingreso,Tipo,NRODOC,Peso,Talla,...,Diagnostico79,NombreDiagnostico79,Diagnostico80,NombreDiagnostico80,Diagnostico81,NombreDiagnostico81,Diagnostico82,NombreDiagnostico82,Diagnostico83,NombreDiagnostico83
0,2017,OCTUBRE,2017-10-02,9:00:20 a. m.,3912499,2629714,CC,311144,69.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017,OCTUBRE,2017-10-02,9:04:33 a. m.,3942247,2629726,CC,308418,62.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017,OCTUBRE,2017-10-02,9:11:43 a. m.,3898560,2629751,CC,308573,89.0,163.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017,OCTUBRE,2017-10-02,9:33:34 a. m.,3912599,2629828,CC,307549,88.0,163.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017,OCTUBRE,2017-10-02,9:43:59 a. m.,3906820,2629717,CC,307044,58.0,158.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
df_usuarios = pd.read_excel('RETO_df_usuarios.xlsx')
df_usuarios.head()

,MES,YEAR,NRODOC,SEXO,FECHA NACIMIENTO,EDAD,DEPARTAMENTO,MUNICIPIO,BARRIO,FECHA INICIO AL PGP,FECHA PRIMERA CLASE FUNCIONAL,PRIMERA CLASE FUNCIONAL,FECHA ÃšLTIMA CLASE FUNCIONAL,ÃšLTIMA CLASE FUNCIONAL,CICLO_VITAL,QUINQUENIO
0,ABRIL,2017,306221,F,1938-09-09,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN
1,ABRIL,2017,306222,F,1974-07-03,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN
2,ABRIL,2017,306223,F,1930-08-24,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN
3,ABRIL,2017,306224,F,1979-12-01,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN
4,ABRIL,2017,306225,M,1943-06-01,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN

In [ ]:
df_egresos = pd.read_excel('RETO_df_egresos.xlsx')
df_egresos.head()

,YEAR,MES,NRO ATENCION,NRO INGRESO,SERVICIO HABILITADO COD,SERVICIO HABILITADO,TIPO IDENTIFICACION,NRODOC,FECHA NACIMIENTO,REGIMEN AFILIACION,...,DX PRINCIPAL EGRESO CAPITULO COD,DX PRINCIPAL EGRESO CAPITULO,CAUSA BASICA MUERTE COD,CAUSA BASICA MUERTE,CAUSA BASICA CATEGORIA COD,CAUSA BASICA CATEGORIA,CAUSA BASICA CAPITULO COD,CAUSA BASICA CAPITULO,PROFESIONAL ESPECIALIDAD,PROFESIONAL ESPECIALIDAD GRD
0,2017,MAYO,3433964,1899917,-1,Sin Informacion,CC,308185,1937-07-18,Sin informaciÃ³n,...,J00-J99,ENFERMEDADES DEL SISTEMA RESPIRATORIO,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,Sin informacion en Base de datos,Medicina Interna
1,2017,DICIEMBRE,3720631,2018136,-1,Sin Informacion,CC,308185,1937-07-18,Sin informaciÃ³n,...,J00-J99,ENFERMEDADES DEL SISTEMA RESPIRATORIO,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,Sin informacion en Base de datos,Medicina Interna
2,2018,FEBRERO,3912821,2159592,501,Urgencias >= 24 horas,CC,308185,1937-07-18,Contributivo,...,J00-J99,ENFERMEDADES DEL SISTEMA RESPIRATORIO,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,Medicina Interna,Urgentologia
3,2018,MAYO,4023613,2254075,501,Urgencias >= 24 horas,CC,308185,1937-07-18,Contributivo,...,I00-I99,ENFERMEDADES DEL SISTEMA CIRCULATORIO,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,Medicina Interna,Urgentologia
4,2018,JULIO,4080166,2292863,101,General adultos,CC,308185,1937-07-18,Contributivo,...,I00-I99,ENFERMEDADES DEL SISTEMA CIRCULATORIO,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,Medicina Interna,Medicina Interna

In [ ]:
 #Se muestra el tamaño de cada base cargada
print(df_cronicos.shape)
print(df_usuarios.shape)
print(df_egresos.shape)

(38717, 290)
(183911, 16)
(6376, 66)

In [ ]:
df_cronicos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38717 entries, 0 to 38716
Columns: 290 entries, YEAR to NombreDiagnostico83
dtypes: datetime64[ns](3), float64(38), int64(11), object(238)
memory usage: 85.7+ MB

In [ ]:
df_usuarios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183911 entries, 0 to 183910
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   MES                            183911 non-null  object
 1   YEAR                           183911 non-null  int64
 2   NRODOC                         183911 non-null  int64
 3   SEXO                           183901 non-null  object
 4   FECHA NACIMIENTO               111831 non-null  datetime64[ns]
 5   EDAD                           149755 non-null  float64
 6   DEPARTAMENTO                   82284 non-null   object
 7   MUNICIPIO                      81397 non-null   object
 8   BARRIO                         115344 non-null  object
 9   FECHA INICIO AL PGP            125658 non-null  datetime64[ns]
 10  FECHA PRIMERA CLASE FUNCIONAL  87961 non-null   object
 11  PRIMERA CLASE FUNCIONAL        89641 non-null   object
 12  FECHA ÃšLTIMA CLASE FUNCIONAL  87985 non-null   datetime64[ns]
 13  ÃšLTIMA CLASE FUNCIONAL        128109 non-null  object
 14  CICLO_VITAL                    149755 non-null  object
 15  QUINQUENIO                     149755 non-null  object
dtypes: datetime64[ns](3), float64(1), int64(2), object(10)
memory usage: 22.5+ MB

In [ ]:
df_egresos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6376 entries, 0 to 6375
Data columns (total 66 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   YEAR                               6376 non-null   int64
 1   MES                                6376 non-null   object
 2   NRO ATENCION                       6376 non-null   int64
 3   NRO INGRESO                        6376 non-null   int64
 4   SERVICIO HABILITADO COD            6376 non-null   int64
 5   SERVICIO HABILITADO                6376 non-null   object
 6   TIPO IDENTIFICACION                6376 non-null   object
 7   NRODOC                             6376 non-null   int64
 8   FECHA NACIMIENTO                   6376 non-null   datetime64[ns]
 9   REGIMEN AFILIACION                 6376 non-null   object
 10  EPS VALIDADA                       4103 non-null   object
 11  MODALIDAD CONTRATO                 6376 non-null   object
 12  FUENTE FINANCIACION1               6376 non-null   object
 13  FUENTE FINANCIACION2               6376 non-null   object
 14  SERVICIO ADMITE                    6376 non-null   object
 15  BLOQUE ANTERIOR                    6376 non-null   object
 16  PISO ANTERIOR                      6376 non-null   object
 17  SERVICIO ANTERIOR                  6376 non-null   object
 18  NRO CAMA ANTERIOR                  6376 non-null   object
 19  VIA INGRESO                        6376 non-null   object
 20  BLOQUE                             6376 non-null   object
 21  UNIDAD ESTRATEGICA                 6376 non-null   object
 22  PISO                               6376 non-null   object
 23  NRO CAMA                           6376 non-null   object
 24  SERVICIO EGRESO                    6376 non-null   object
 25  TIPO EGRESO                        6376 non-null   object
 26  FECHA INGRESO CLINICA              4105 non-null   datetime64[ns]
 27  FECHA INGRESO SERVICIO             4104 non-null   datetime64[ns]
 28  FECHA POSIBLE ALTA                 153 non-null    datetime64[ns]
 29  FECHA ALTA MEDICA                  6376 non-null   datetime64[ns]
 30  FECHA RECAUDO                      1599 non-null   datetime64[ns]
 31  FECHA CAMILLERO                    1836 non-null   datetime64[ns]
 32  FECHA ENFERMERIA                   1453 non-null   datetime64[ns]
 33  FECHA FACTURACION AUDIFARMA        2080 non-null   datetime64[ns]
 34  FECHA FARMACIA                     2061 non-null   datetime64[ns]
 35  FECHA SALIDA                       6376 non-null   datetime64[ns]
 36  FECHA ASEO                         1981 non-null   datetime64[ns]
 37  DEMORA ASIGNACION CAMA             6376 non-null   object
 38  DEMORA APLICACION MEDICAMENTO      6359 non-null   object
 39  DEMORA SALIDA CLINICA (DIAS)       6376 non-null   int64
 40  TRANSFUSION SANGRE                 6376 non-null   object
 41  ANTIBIOTICO                        6376 non-null   object
 42  ALTA MEDICA                        6376 non-null   object
 43  POSIBLE ALTA                       6376 non-null   object
 44  DXPRINCIPAL EGRESO COD             6376 non-null   object
 45  DXPRINCIPAL EGRESO                 6376 non-null   object
 46  DX RELACIONADO1 COD                6357 non-null   object
 47  DX RELACIONADO1                    6376 non-null   object
 48  DX RELACIONADO2 COD                6309 non-null   object
 49  DX RELACIONADO2                    6376 non-null   object
 50  DX RELACIONADO3 COD                6195 non-null   object
 51  DX RELACIONADO3                    6376 non-null   object
 52  TIPO DIAGNOSTICO PRINCIPAL         6376 non-null   object
 53  PERTINENCIA DIAGNOSTICA            1184 non-null   object
 54  DX PRINCIPAL EGRESO CATEGORIA COD  6304 non-null   object
 55  DX PRINCIPAL EGRESO CATEGORIA      6376 non-null   object
 56  DX PRINCIPAL EGRESO CAPITULO COD   6304 non-null   object
 57  DX PRINCIPAL EGRESO CAPITULO       6376 non-null   object
 58  CAUSA BASICA MUERTE COD            566 non-null    object
 59  CAUSA BASICA MUERTE                6376 non-null   object
 60  CAUSA BASICA CATEGORIA COD         564 non-null    object
 61  CAUSA BASICA CATEGORIA             6376 non-null   object
 62  CAUSA BASICA CAPITULO COD          564 non-null    object
 63  CAUSA BASICA CAPITULO              6376 non-null   object
 64  PROFESIONAL ESPECIALIDAD           6376 non-null   object
 65  PROFESIONAL ESPECIALIDAD GRD       6376 non-null   object
dtypes: datetime64[ns](12), int64(6), object(48)
memory usage: 3.2+ MB

In [47]:
df_cronicos.isnull().sum()

YEAR                          0
MES                           0
Fecha diligenciamiento        0
Hora                          0
AtenciÃ³n                     0
                          ...
NombreDiagnostico81       38702
Diagnostico82             38704
NombreDiagnostico82       38704
Diagnostico83             38704
NombreDiagnostico83       38704
Length: 290, dtype: int64

In [72]:
##Eliminar las columnas que contienen más de un umbral de valores nulos.
##El umbral se definió en 0,2 porque consideramos que las columnas que tengan mas del 80 por ciento de sus datos nulos no aportan al desarrollo del modelo
def eliminar_columnas_con_nulos(df, umbral=0.2):
    
    # Calcula la proporción de valores nulos en cada columna
    proporciones_nulos = df.isnull().mean()
    
    # Filtra las columnas que tienen un porcentaje de valores nulos mayor que el umbral
    columnas_a_eliminar = proporciones_nulos[proporciones_nulos > umbral].index
    
    # Elimina las columnas con valores nulos
    df_sin_nulos = df.drop(columns=columnas_a_eliminar)
    
    return df_sin_nulos

In [86]:
##Eliminar las columnas de df_cronicos que contengan mas del 80% de nulos
cronicos = eliminar_columnas_con_nulos(df_cronicos)
cronicos.head()

,YEAR,MES,Fecha diligenciamiento,Hora,AtenciÃ³n,Ingreso,Tipo,NRODOC,Peso,Talla,IMC,ClasificaciÃ³n IMC,SaturaciÃ³n de OxÃ­geno (%),PerÃ­metro Muslo,PerÃ­metro Cintura,Pliegue Triceps,Pliegue Abdomen,Pliegue Muslo,Sumatoria Pliegues,PresiÃ³n Arterial SistÃ³lica,PresiÃ³n Arterial DiastÃ³lica,Frecuencia CardÃ­aca en reposo,Auto-calificacion Nivel de Ejercicio,Constantes,METS -Ãndice MetabÃ³lico,VO2 - MÃ¡xima Cantidad de OxÃ­geno,Ãndice de Fragilidad Groningen,CalificaciÃ³n (Ãndice de Fragilidad),Tiempo en Segundos (Apoyo Monopodal),CalificaciÃ³n (Apoyo Monopodal),Tiempo en Segundos (Recorrer 5 metros),Velocidad (m/s),CalificaciÃ³n Velocidad,Diabetes Mellitus,Glicemia,Fecha glicemia,Hemoglobina Glicada,Fecha hemoglobina glicosilada,Control Diabetes,Tiene HTA,Tiempo con el diagnÃ³stico1,Tiene EPOC,Enfermedad Coronaria (En el Ãºltimo aÃ±o),Insuficiencia CardÃ­aca,ValvulopatÃ­a,Arritmia o paciente con dispositivo,Sufre de alguna enfermedad cardiovascular,Tabaquismo,Cuantos cigarrillos dÃ­a,Lipoproteina,HDL,Fecha HDL,Colesterol total,Fecha colesterol total,Trigliceridos,Fecha trigliceridos,Creatinina 1 consulta,Fecha creatinina1,Tasa de FiltraciÃ³n Glomerular TFG,Estadio de la Enfermedad Renal,Microalbuminuria,Fecha microalbuminuria,Hormona Estimulante de la Tiroides (TSH),Clase Funcional,Creatinina 2 consulta,Tasa de FiltraciÃ³n Glomerular TFG2,Meses de diferencia entre TFG,Cambio de TFG,Ãšlcera de pie diabÃ©tico,RemisiÃ³n,DiagnÃ³stico Principal,AnÃ¡lisis y conducta a seguir
0,2017,OCTUBRE,2017-10-02,9:00:20 a. m.,3912499,2629714,CC,311144,69.0,155.0,28.72,Sobrepeso,91.0,51,109.0,10.0,25.0,5.0,40.0,140,77,66,3,1.06,6.3376,22.1816,3.0,FrÃ¡gil,15,Aceptable,5,1.00,Aceptable,Si,0.0,ND,8.15,ND,No controlada,Si,ND,No,No aplica,No aplica,No,No,No,Si,ND,60.68,53.95,ND,128.0,ND,67.33,ND,0.68,ND,63.49,Estadio 2,56.55,ND,5.05,Clase funcional 2B,0.0,0.0,0.0,0.0,No,Grupal 2,I10X - HIPERTENSION ESENCIAL (PRIMARIA),ESTADIO RENAL 2 A3?RCV a 10 aÃ±os MODERADO **C...
1,2017,OCTUBRE,2017-10-02,9:04:33 a. m.,3942247,2629726,CC,308418,62.0,155.0,25.81,Sobrepeso,94.0,60,89.0,25.0,35.0,20.0,80.0,181,143,90,2,0.32,4.1023,14.3580,6.0,FrÃ¡gil,1,Malo - Fragil,7,0.71,Deficiente,No,98.0,ND,0.00,ND,No aplica,Si,ND,Si,No aplica,No aplica,No,No,No,No,ND,92.00,45.00,ND,157.0,ND,103.00,ND,0.85,ND,58.56,Estadio 3A,0.00,ND,4.65,Clase funcional 2A,0.0,0.0,0.0,0.0,No,Grupal 2,I10X - HIPERTENSION ESENCIAL (PRIMARIA),"Paciente 72 aÃ±os, Antecedente de. 1. HTA 2. E..."
2,2017,OCTUBRE,2017-10-02,9:11:43 a. m.,3898560,2629751,CC,308573,89.0,163.0,33.50,Obesidad Grasa,96.0,65,113.0,10.0,30.0,5.0,45.0,154,102,75,2,0.32,7.0150,24.5525,5.0,FrÃ¡gil,20,Aceptable,5,1.00,Aceptable,No,107.0,ND,0.00,ND,No aplica,Si,ND,No,No aplica,No aplica,No,No,Si,Si,ND,43.00,30.00,ND,115.0,ND,204.00,ND,1.32,ND,62.09,Estadio 2,12.00,ND,5.41,Clase funcional 2B,0.0,0.0,0.0,0.0,No,Grupal 2,I10X - HIPERTENSION ESENCIAL (PRIMARIA),paciente con RCV alto por antecednete de enf. ...
3,2017,OCTUBRE,2017-10-02,9:33:34 a. m.,3912599,2629828,CC,307549,88.0,163.0,33.12,Obesidad Grasa,73.0,66,108.0,8.0,10.0,5.0,23.0,128,71,94,2,0.32,5.3096,18.5836,2.0,FrÃ¡gil,30,Bueno,5,1.00,Aceptable,No,0.0,ND,0.00,ND,No aplica,Si,ND,Si,No aplica,No aplica,No,No,No,No,ND,102.00,41.00,ND,170.0,ND,138.00,ND,1.00,ND,68.57,Estadio 2,3.56,ND,13.73,Clase funcional 2B,0.0,0.0,0.0,0.0,No,Grupal 2,I10X - HIPERTENSION ESENCIAL (PRIMARIA),ESTADIO renal 2A1?RCV a 10 aÃ±os 16 % **CLASIF...
4,2017,OCTUBRE,2017-10-02,9:43:59 a. m.,3906820,2629717,CC,307044,58.0,158.0,23.23,Normal,97.0,59,90.0,10.0,20.0,20.0,50.0,126,56,56,2,0.32,7.5309,26.3581,7.0,FrÃ¡gil,1,Malo - Fragil,6,0.83,Deficiente,No,100.0,ND,0.00,ND,No aplica,Si,ND,Si,No aplica,Controlada,No,No,Si,No,ND,30.00,68.00,ND,110.0,ND,0.00,ND,1.39,ND,29.56,Estadio 4,0.00,ND,0.00,Clase funcional 3,0.0,0.0,0.0,0.0,No,Grupal 3,I10X - HIPERTENSION ESENCIAL (PRIMARIA),"Paciente de 80 aÃ±os de edad, Con antecedentes..."

In [88]:
nuloscronicos=cronicos.isnull().sum().sort_values(ascending=False)
nuloscronicos.head(20)

Tiempo con el diagnÃ³stico1       7003
Fecha microalbuminuria            4819
Fecha hemoglobina glicosilada     3631
Ãšlcera de pie diabÃ©tico         3505
Estadio de la Enfermedad Renal    3248
Fecha glicemia                    2454
Fecha trigliceridos               2323
Fecha colesterol total            2274
Fecha HDL                         2249
Fecha creatinina1                 1786
DiagnÃ³stico Principal            1350
AnÃ¡lisis y conducta a seguir     1097
Microalbuminuria                  1053
Colesterol total                  1053
Clase Funcional                   1053
Tabaquismo                        1053
Cambio de TFG                     1053
HDL                               1053
Creatinina 2 consulta             1053
Lipoproteina                      1053
dtype: int64

In [106]:
cronicos.dtypes.head(20)

YEAR                                     int64
MES                                     object
Fecha diligenciamiento          datetime64[ns]
Hora                                    object
AtenciÃ³n                                int64
Ingreso                                  int64
Tipo                                    object
NRODOC                                   int64
Peso                                   float64
Talla                                  float64
IMC                                    float64
ClasificaciÃ³n IMC                      object
SaturaciÃ³n de OxÃ­geno (%)            float64
PerÃ­metro Muslo                         int64
PerÃ­metro Cintura                     float64
Pliegue Triceps                        float64
Pliegue Abdomen                        float64
Pliegue Muslo                          float64
Sumatoria Pliegues                     float64
PresiÃ³n Arterial SistÃ³lica             int64
dtype: object

In [ ]:
#Definir imputer para variables numéricas
imp_num = SimpleImputer(strategy='most_frequent')
#Ajustar imputer y transformar las variables con valores null
cronicos['EnvironmentSatisfaction']= imp_num.fit_transform(cronicos['EnvironmentSatisfaction'].values.reshape(-1,1))

In [85]:
##Mostrar todas las columnas 
pd.options.display.max_columns = None
cronicos.head(2)

,YEAR,MES,Fecha diligenciamiento,Hora,AtenciÃ³n,Ingreso,Tipo,NRODOC,Peso,Talla,IMC,ClasificaciÃ³n IMC,SaturaciÃ³n de OxÃ­geno (%),PerÃ­metro Muslo,PerÃ­metro Cintura,Pliegue Triceps,Pliegue Abdomen,Pliegue Muslo,Sumatoria Pliegues,PresiÃ³n Arterial SistÃ³lica,PresiÃ³n Arterial DiastÃ³lica,Frecuencia CardÃ­aca en reposo,Auto-calificacion Nivel de Ejercicio,Constantes,METS -Ãndice MetabÃ³lico,VO2 - MÃ¡xima Cantidad de OxÃ­geno,Ãndice de Fragilidad Groningen,CalificaciÃ³n (Ãndice de Fragilidad),Tiempo en Segundos (Apoyo Monopodal),CalificaciÃ³n (Apoyo Monopodal),Tiempo en Segundos (Recorrer 5 metros),Velocidad (m/s),CalificaciÃ³n Velocidad,Diabetes Mellitus,Glicemia,Fecha glicemia,Hemoglobina Glicada,Fecha hemoglobina glicosilada,Control Diabetes,Tiene HTA,Tiempo con el diagnÃ³stico1,Tiene EPOC,Enfermedad Coronaria (En el Ãºltimo aÃ±o),Insuficiencia CardÃ­aca,ValvulopatÃ­a,Arritmia o paciente con dispositivo,Sufre de alguna enfermedad cardiovascular,Tabaquismo,Cuantos cigarrillos dÃ­a,Lipoproteina,HDL,Fecha HDL,Colesterol total,Fecha colesterol total,Trigliceridos,Fecha trigliceridos,Creatinina 1 consulta,Fecha creatinina1,Tasa de FiltraciÃ³n Glomerular TFG,Estadio de la Enfermedad Renal,Microalbuminuria,Fecha microalbuminuria,Hormona Estimulante de la Tiroides (TSH),Clase Funcional,Creatinina 2 consulta,Tasa de FiltraciÃ³n Glomerular TFG2,Meses de diferencia entre TFG,Cambio de TFG,Ãšlcera de pie diabÃ©tico,RemisiÃ³n,DiagnÃ³stico Principal,AnÃ¡lisis y conducta a seguir
0,2017,OCTUBRE,2017-10-02,9:00:20 a. m.,3912499,2629714,CC,311144,69.0,155.0,28.72,Sobrepeso,91.0,51,109.0,10.0,25.0,5.0,40.0,140,77,66,3,1.06,6.3376,22.1816,3.0,FrÃ¡gil,15,Aceptable,5,1.00,Aceptable,Si,0.0,ND,8.15,ND,No controlada,Si,ND,No,No aplica,No aplica,No,No,No,Si,ND,60.68,53.95,ND,128.0,ND,67.33,ND,0.68,ND,63.49,Estadio 2,56.55,ND,5.05,Clase funcional 2B,0.0,0.0,0.0,0.0,No,Grupal 2,I10X - HIPERTENSION ESENCIAL (PRIMARIA),ESTADIO RENAL 2 A3?RCV a 10 aÃ±os MODERADO **C...
1,2017,OCTUBRE,2017-10-02,9:04:33 a. m.,3942247,2629726,CC,308418,62.0,155.0,25.81,Sobrepeso,94.0,60,89.0,25.0,35.0,20.0,80.0,181,143,90,2,0.32,4.1023,14.3580,6.0,FrÃ¡gil,1,Malo - Fragil,7,0.71,Deficiente,No,98.0,ND,0.00,ND,No aplica,Si,ND,Si,No aplica,No aplica,No,No,No,No,ND,92.00,45.00,ND,157.0,ND,103.00,ND,0.85,ND,58.56,Estadio 3A,0.00,ND,4.65,Clase funcional 2A,0.0,0.0,0.0,0.0,No,Grupal 2,I10X - HIPERTENSION ESENCIAL (PRIMARIA),"Paciente 72 aÃ±os, Antecedente de. 1. HTA 2. E..."

In [107]:
##Eliminar las columnas de df_usuarios que contengan mas del 80% de nulos
usuarios = eliminar_columnas_con_nulos(df_usuarios)
usuarios.head()

     MES  YEAR  NRODOC SEXO  EDAD CICLO_VITAL QUINQUENIO
0  ABRIL  2017  306221    F   NaN         NaN        NaN
1  ABRIL  2017  306222    F   NaN         NaN        NaN
2  ABRIL  2017  306223    F   NaN         NaN        NaN
3  ABRIL  2017  306224    F   NaN         NaN        NaN
4  ABRIL  2017  306225    M   NaN         NaN        NaN

In [109]:
nulosusuarios=usuarios.isnull().sum().sort_values(ascending=False)
nulosusuarios

EDAD           34156
CICLO_VITAL    34156
QUINQUENIO     34156
SEXO              10
MES                0
YEAR               0
NRODOC             0
dtype: int64

In [110]:
#Eliminar las columnas CICLO_VITAL y QUINQUENIO ya que aportan información sobre la edad separada por categorías
usuarios2 = usuarios.drop(['CICLO_VITAL','QUINQUENIO'], axis = 1)

In [111]:
usuarios2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183911 entries, 0 to 183910
Data columns (total 5 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   MES     183911 non-null  object
 1   YEAR    183911 non-null  int64
 2   NRODOC  183911 non-null  int64
 3   SEXO    183901 non-null  object
 4   EDAD    149755 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 7.0+ MB

In [118]:
##Eliminar las columnas de df_egresos que contengan mas del 80% de nulos
egresos = eliminar_columnas_con_nulos(df_egresos)
egresos.head(3)

,YEAR,MES,NRO ATENCION,NRO INGRESO,SERVICIO HABILITADO COD,SERVICIO HABILITADO,TIPO IDENTIFICACION,NRODOC,FECHA NACIMIENTO,REGIMEN AFILIACION,MODALIDAD CONTRATO,FUENTE FINANCIACION1,FUENTE FINANCIACION2,SERVICIO ADMITE,BLOQUE ANTERIOR,PISO ANTERIOR,SERVICIO ANTERIOR,NRO CAMA ANTERIOR,VIA INGRESO,BLOQUE,UNIDAD ESTRATEGICA,PISO,NRO CAMA,SERVICIO EGRESO,TIPO EGRESO,FECHA ALTA MEDICA,FECHA SALIDA,DEMORA ASIGNACION CAMA,DEMORA APLICACION MEDICAMENTO,DEMORA SALIDA CLINICA (DIAS),TRANSFUSION SANGRE,ANTIBIOTICO,ALTA MEDICA,POSIBLE ALTA,DXPRINCIPAL EGRESO COD,DXPRINCIPAL EGRESO,DX RELACIONADO1 COD,DX RELACIONADO1,DX RELACIONADO2 COD,DX RELACIONADO2,DX RELACIONADO3 COD,DX RELACIONADO3,TIPO DIAGNOSTICO PRINCIPAL,DX PRINCIPAL EGRESO CATEGORIA COD,DX PRINCIPAL EGRESO CATEGORIA,DX PRINCIPAL EGRESO CAPITULO COD,DX PRINCIPAL EGRESO CAPITULO,CAUSA BASICA MUERTE,CAUSA BASICA CATEGORIA,CAUSA BASICA CAPITULO,PROFESIONAL ESPECIALIDAD,PROFESIONAL ESPECIALIDAD GRD
0,2017,MAYO,3433964,1899917,-1,Sin Informacion,CC,308185,1937-07-18,Sin informaciÃ³n,Sin informaciÃ³n,Sin informaciÃ³n,Sin informaciÃ³n,Urgencias Generales SÃ³tano,Sin Informacion,Sin Informacion,Sin Informacion,Sin Informacion,Sin informacion en Base de datos,Sin Informacion,Hospitalizacion Adultos,Sin Informacion,Sin Informacion,Sin Informacion,Sin informaciÃ³n,2017-05-17 09:03:57.637,2017-05-17 10:55:02,00:00:00,00:00:00,0,NO,NO,Sin Informacion,Sin Informacion,J441,ENFERMEDAD PULMONAR OBSTRUCTIVA CRONICA CON EX...,J984,OTROS TRASTORNOS DEL PULMON,J432,ENFISEMA CENTROLOBULAR,J981,COLAPSO PULMONAR,Sin Informacion,J44,OTRAS ENFERMEDADES PULMONARES OBSTRUCTIVAS CRO...,J00-J99,ENFERMEDADES DEL SISTEMA RESPIRATORIO,Sin informacion en base de datos,Sin informacion en base de datos,Sin informacion en base de datos,Sin informacion en Base de datos,Medicina Interna
1,2017,DICIEMBRE,3720631,2018136,-1,Sin Informacion,CC,308185,1937-07-18,Sin informaciÃ³n,Sin informaciÃ³n,Sin informaciÃ³n,Sin informaciÃ³n,Urgencias Generales SÃ³tano,Sin Informacion,Sin Informacion,Sin Informacion,Sin Informacion,Sin informacion en Base de datos,Sin Informacion,Hospitalizacion Adultos,Sin Informacion,Sin Informacion,Sin Informacion,Sin informaciÃ³n,2017-12-07 09:35:27.147,2017-12-07 11:06:49,00:00:00,00:00:00,0,NO,NO,Sin Informacion,Sin Informacion,J441,ENFERMEDAD PULMONAR OBSTRUCTIVA CRONICA CON EX...,J960,INSUFICIENCIA RESPIRATORIA AGUDA,I110,ENFERMEDAD CARDIACA HIPERTENSIVA CON INSUFICIE...,I270,HIPERTENSION PULMONAR PRIMARIA,Sin Informacion,J44,OTRAS ENFERMEDADES PULMONARES OBSTRUCTIVAS CRO...,J00-J99,ENFERMEDADES DEL SISTEMA RESPIRATORIO,Sin informacion en base de datos,Sin informacion en base de datos,Sin informacion en base de datos,Sin informacion en Base de datos,Medicina Interna
2,2018,FEBRERO,3912821,2159592,501,Urgencias >= 24 horas,CC,308185,1937-07-18,Contributivo,PGP,NUEVA EPS,NUEVA EPS,Urgencias Generales SÃ³tano,Sin Informacion,Sin Informacion,Sin Informacion,Sin Informacion,Urgencias,Bloque 3,Urgencias,Urgencias,FST101,Fast track 1,Alta MÃ©dica,2018-02-22 13:05:00.000,2018-02-22 13:21:18,00:00:00,0,0,NO,SI,SI,Sin Informacion,J441,ENFERMEDAD PULMONAR OBSTRUCTIVA CRONICA CON EX...,J980,ENFERMEDADES DE LA TRAQUEA Y DE LOS BRONQUIOS ...,I10X,HIPERTENSION ESENCIAL (PRIMARIA),E872,ACIDOSIS,Repetido,J44,OTRAS ENFERMEDADES PULMONARES OBSTRUCTIVAS CRO...,J00-J99,ENFERMEDADES DEL SISTEMA RESPIRATORIO,Sin informacion en base de datos,Sin informacion en base de datos,Sin informacion en base de datos,Medicina Interna,Urgentologia

In [113]:
nulosegresos=egresos.isnull().sum().sort_values(ascending=False)
nulosegresos

DX RELACIONADO3 COD                  181
DX PRINCIPAL EGRESO CAPITULO COD      72
DX PRINCIPAL EGRESO CATEGORIA COD     72
DX RELACIONADO2 COD                   67
DX RELACIONADO1 COD                   19
DEMORA APLICACION MEDICAMENTO         17
YEAR                                   0
DX RELACIONADO1                        0
DEMORA SALIDA CLINICA (DIAS)           0
TRANSFUSION SANGRE                     0
ANTIBIOTICO                            0
ALTA MEDICA                            0
POSIBLE ALTA                           0
DXPRINCIPAL EGRESO COD                 0
DXPRINCIPAL EGRESO                     0
DX RELACIONADO2                        0
MES                                    0
DX RELACIONADO3                        0
TIPO DIAGNOSTICO PRINCIPAL             0
DX PRINCIPAL EGRESO CATEGORIA          0
DX PRINCIPAL EGRESO CAPITULO           0
CAUSA BASICA MUERTE                    0
CAUSA BASICA CATEGORIA                 0
CAUSA BASICA CAPITULO                  0
PROFESIONAL ESPECIALIDAD               0
DEMORA ASIGNACION CAMA                 0
FECHA SALIDA                           0
FECHA ALTA MEDICA                      0
FUENTE FINANCIACION2                   0
NRO ATENCION                           0
NRO INGRESO                            0
SERVICIO HABILITADO COD                0
SERVICIO HABILITADO                    0
TIPO IDENTIFICACION                    0
NRODOC                                 0
FECHA NACIMIENTO                       0
REGIMEN AFILIACION                     0
MODALIDAD CONTRATO                     0
FUENTE FINANCIACION1                   0
SERVICIO ADMITE                        0
TIPO EGRESO                            0
BLOQUE ANTERIOR                        0
PISO ANTERIOR                          0
SERVICIO ANTERIOR                      0
NRO CAMA ANTERIOR                      0
VIA INGRESO                            0
BLOQUE                                 0
UNIDAD ESTRATEGICA                     0
PISO                                   0
NRO CAMA                               0
SERVICIO EGRESO                        0
PROFESIONAL ESPECIALIDAD GRD           0
dtype: int64

In [19]:
df2=pd.merge(df_cronicos, df_usuarios, how = 'inner', on = 'NRODOC').merge(df_egresos, how = 'inner', on = 'NRODOC')

In [21]:
df2

,YEAR_x,MES_x,Fecha diligenciamiento,Hora,AtenciÃ³n,Ingreso,Tipo,NRODOC,Peso,Talla,...,DX PRINCIPAL EGRESO CAPITULO COD,DX PRINCIPAL EGRESO CAPITULO,CAUSA BASICA MUERTE COD,CAUSA BASICA MUERTE,CAUSA BASICA CATEGORIA COD,CAUSA BASICA CATEGORIA,CAUSA BASICA CAPITULO COD,CAUSA BASICA CAPITULO,PROFESIONAL ESPECIALIDAD,PROFESIONAL ESPECIALIDAD GRD
0,2017,OCTUBRE,2017-10-02,9:04:33 a. m.,3942247,2629726,CC,308418,62.0,155.0,...,I00-I99,ENFERMEDADES DEL SISTEMA CIRCULATORIO,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,Sin informacion en Base de datos,Medicina Interna
1,2017,OCTUBRE,2017-10-02,9:04:33 a. m.,3942247,2629726,CC,308418,62.0,155.0,...,J00-J99,ENFERMEDADES DEL SISTEMA RESPIRATORIO,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,Sin informacion en Base de datos,Medicina Interna
2,2017,OCTUBRE,2017-10-02,9:04:33 a. m.,3942247,2629726,CC,308418,62.0,155.0,...,J00-J99,ENFERMEDADES DEL SISTEMA RESPIRATORIO,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,Medicina Interna,Medicina Interna
3,2017,OCTUBRE,2017-10-02,9:04:33 a. m.,3942247,2629726,CC,308418,62.0,155.0,...,J00-J99,ENFERMEDADES DEL SISTEMA RESPIRATORIO,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,Medicina Interna,Medicina Interna
4,2017,OCTUBRE,2017-10-02,9:04:33 a. m.,3942247,2629726,CC,308418,62.0,155.0,...,J00-J99,ENFERMEDADES DEL SISTEMA RESPIRATORIO,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,Medicina Interna,Medicina Interna
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048272,2022,MARZO,2022-03-01,3:49:10 p.m.,5981581,4240411,CC,308096,70.0,168.0,...,F00-F99,TRASTORNOS MENTALES Y DEL COMPORTAMIENTO,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,Psiquiatria,Psiquiatria
1048273,2022,MARZO,2022-03-01,3:49:10 p.m.,5981581,4240411,CC,308096,70.0,168.0,...,U00-U99,CODIGOS PARA PROPOSITOS ESPECIALES,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,Medicina Interna,Infectologia
1048274,2022,MARZO,2022-03-01,3:49:10 p.m.,5981581,4240411,CC,308096,70.0,168.0,...,F00-F99,TRASTORNOS MENTALES Y DEL COMPORTAMIENTO,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,Psiquiatria,Psiquiatria
1048275,2022,MARZO,2022-03-01,3:49:10 p.m.,5981581,4240411,CC,308096,70.0,168.0,...,U00-U99,CODIGOS PARA PROPOSITOS ESPECIALES,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,Medicina Interna,Infectologia
1048276,2022,MARZO,2022-03-01,3:49:10 p.m.,5981581,4240411,CC,308096,70.0,168.0,...,F00-F99,TRASTORNOS MENTALES Y DEL COMPORTAMIENTO,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,NaN,Sin informacion en base de datos,Psiquiatria,Psiquiatria

In [12]:
df2['NRODOC'].value_counts

<bound method IndexOpsMixin.value_counts of 0          311144
1          311144
2          311144
3          311144
4          311144
            ...
1715744    311850
1715745    311850
1715746    311850
1715747    311850
1715748    311850
Name: NRODOC, Length: 1715749, dtype: int64>

In [17]:
# Veamos las estadísticas

df_encounters_check = df2.groupby(['NRODOC']).agg(encounters = ('NRO INGRESO', 'count')).reset_index().sort_values(['encounters'], ascending = False)
df_encounters_check

      NRODOC  encounters
1478  308373        7605
415   306827        5148
2043  309141        4914
3121  310707        4563
639   307148        4368
...      ...         ...
2712  310121           0
2713  310122           0
2715  310124           0
2716  310125           0
6098  314220           0

[6099 rows x 2 columns]